spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
      url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#server:
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit